import { IDataTableItem } from '@/models/data-table.model';

export const MOCK_DATA_TABLE_ITEMS: IDataTableItem[] = [
  {
    name: 'InvasionAsia9',
    ipAddress: '103.161.224.194',
    port: 1238,
    mapId: 'media/packages/vanilla/maps/map13_2',
    mapName: '',
    bots: 152,
    country: 'Asia',
    currentPlayers: 32,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [
      'MLINH',
      'FRESHBAIT_1087',
      'DELTADAGGER',
      'QRQRQRQQERR',
      'MAXNUR',
      'MADAO24543',
      'SHIDO',
      'DARKFORCE0245',
      'XIAOJUHUA',
      'ROCHELLE',
      'MIYING',
      'COMRADE GENERAL',
      'MR. 47',
      'FZ555',
      'ZANJIAKESHIHELUO',
      'TUZKIZZZZZZ',
      'MR.KD',
      'JIANG ZE MIN',
      'MR. SUNNYSKY',
      'DRAGOMIR',
      'LT',
      'DAWY',
      'THEGOODGUY',
      'BXWL',
      'DNF6516',
      'DERZOM',
      'SHUAIXIONG',
      '32431',
      'TW CYC',
      'TOMARI',
      'XIU_MENG',
      'MCLONGCAO',
    ],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '1',
  },
  {
    name: 'InvasionASIA6',
    ipAddress: '103.161.224.194',
    port: 1235,
    mapId: 'media/packages/vanilla/maps/map18',
    mapName: '',
    bots: 246,
    country: 'Asia',
    currentPlayers: 14,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [
      'BIG JJ YAODAOJI',
      'THAT_NOOB',
      'ARCTIC HARE',
      'SHAYMIN_OF_DAWN',
      'DIAMOND DOGS',
      'NORMACU',
      'DAIHOMEI',
      'GBULIN',
      'TAISUI',
      '252',
      'CHAOFAN',
      'FN57',
      'PRST',
      'SHENYING',
    ],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 24,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '2',
  },
  {
    name: '[地狱潜兵] 难度 15-地狱2服',
    ipAddress: '115.238.185.155',
    port: 1250,
    mapId: 'media/packages/hell_diver/maps/def_lab_koth',
    mapName: '',
    bots: 280,
    country: 'Not set',
    currentPlayers: 11,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [
      'XENOSPHERE',
      'BUYLIJIE',
      'ZAKO',
      '3.141',
      'TANG',
      'CALVELAND',
      'MR. LH',
      'CURRYCHEESE',
      'FFSFJI',
      'DUOLUO',
      'SPARROW',
    ],
    comment: '地狱潜兵模组  QQ：498520233 1倍XP',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2910392031',
    maxPlayers: 20,
    mode: 'HD L15',
    realm: '',
    id: '3',
  },
  {
    name: '[Castling][Temp LV4]',
    ipAddress: '49.235.149.243',
    port: 1235,
    mapId: 'media/packages/GFL_Castling/maps/map17',
    mapName: '',
    bots: 165,
    country: 'China',
    currentPlayers: 10,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [
      'CHILUNC',
      '0FENG0',
      'ROUWAN',
      'ANDER',
      'HKVIT',
      'LJ.ROOKIE',
      'MR. INFINITY',
      'XIN__YUN',
      'GRAYGOO.401',
      'FUMOSITY',
    ],
    comment:
      'Read server rules in our discord: discord.gg/wwUM3kYmRC, QQ Group: 706234535',
    url: 'https://castling.fandom.com/wiki/Castling_Wiki',
    maxPlayers: 20,
    mode: 'Castling',
    realm: '',
    id: '4',
  },
  {
    name: 'InvasionEU2',
    ipAddress: '185.107.96.42',
    port: 1235,
    mapId: 'media/packages/vanilla.desert/maps/map6',
    mapName: '',
    bots: 138,
    country: 'Germany',
    currentPlayers: 10,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [
      'DANNYBROWN',
      'CPT. BABRIEL',
      'JAGUARCHANGEL',
      'MR. GREEN6776767',
      'MR.MISKATA',
      'MR. MOREGREEN',
      'MR. MIHAIL',
      'LUXURE',
      'MR. DINGZIJUN',
      'ORD',
    ],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '5',
  },
  {
    name: 'WW2InvasionCN2',
    ipAddress: '47.107.163.15',
    port: 1280,
    mapId: 'media/packages/pacific/maps/island2',
    mapName: '',
    bots: 127,
    country: 'China',
    currentPlayers: 10,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [
      'E=MC^2',
      'MR. IKUNGG',
      'IVY',
      'HOMO1453',
      'ZPKT',
      'STS',
      'LANSL',
      'WWAM',
      'MR. PE',
      'ALUGUN',
    ],
    comment: 'WW2 Coop campaign',
    url: '',
    maxPlayers: 24,
    mode: 'COOP',
    realm: 'official_pacific',
    id: '6',
  },
  {
    name: '[Castling][Hell-6 LV4]',
    ipAddress: '222.131.204.76',
    port: 21001,
    mapId: 'media/packages/GFL_Castling/maps/map1_2',
    mapName: '',
    bots: 294,
    country: 'China',
    currentPlayers: 8,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [
      'GAMBO',
      'MR. 7355608',
      'WHAT?HAHA',
      'LG0394',
      'DCD',
      'KAROS',
      'MAKROV',
      'NTRTOOL',
    ],
    comment:
      'Read server rules in our discord: discord.gg/wwUM3kYmRC, QQ Group: 706234535',
    url: 'https://castling.fandom.com/wiki/Castling_Wiki',
    maxPlayers: 20,
    mode: 'Castling',
    realm: '',
    id: '7',
  },
  {
    name: 'InvasionJP1',
    ipAddress: '45.32.63.85',
    port: 1234,
    mapId: 'media/packages/vanilla/maps/map1_2',
    mapName: '',
    bots: 183,
    country: 'Japan',
    currentPlayers: 8,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [
      'AIDA',
      'SIXSIXSIXSOX',
      'VEILSIDE',
      'KILLER WIND',
      'BOY ZHU',
      'MR. QIAN',
      'GERALD LIU',
      'CARBENE',
    ],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '8',
  },
  {
    name: 'InvasionASIA5',
    ipAddress: '103.161.224.194',
    port: 1234,
    mapId: 'media/packages/vanilla/maps/map19',
    mapName: '',
    bots: 292,
    country: 'Asia',
    currentPlayers: 5,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['SOPHIA', 'GARUDA', 'DFAFA', 'MR. GOODCHALLENG', 'DR .ZHOU'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '9',
  },
  {
    name: 'InvasionASIA7',
    ipAddress: '103.161.224.194',
    port: 1236,
    mapId: 'media/packages/vanilla/maps/map19',
    mapName: '',
    bots: 292,
    country: 'Asia',
    currentPlayers: 4,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['F.QIANMENG', 'MR. GREENTTTT', 'CC1992125', 'GUOYI'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '10',
  },
  {
    name: 114514,
    ipAddress: '39.189.60.211',
    port: 6447,
    mapId: 'media/packages/vanilla.desert/maps/map10',
    mapName: '',
    bots: 213,
    country: 'Not set',
    currentPlayers: 3,
    version: '1.98.1',
    dedicated: false,
    mod: 0,
    playerList: ['MR. GREEN', 'YYDLZ', 'JIANG XUE'],
    comment: '',
    url: '',
    maxPlayers: 64,
    mode: '',
    realm: '',
    id: '11',
  },
  {
    name: 114514,
    ipAddress: '183.158.39.96',
    port: 1234,
    mapId: 'media/packages/vanilla.winter/maps/map12',
    mapName: '',
    bots: 33,
    country: 'Not set',
    currentPlayers: 3,
    version: '1.98.1',
    dedicated: false,
    mod: 0,
    playerList: ['MR. GREEN', 'XY', 'DOCTOR'],
    comment: '',
    url: '',
    maxPlayers: 3,
    mode: '',
    realm: '',
    id: '12',
  },
  {
    name: 'InvasionASIA10',
    ipAddress: '103.161.224.194',
    port: 1239,
    mapId: 'media/packages/vanilla/maps/map19',
    mapName: '',
    bots: 292,
    country: 'Asia',
    currentPlayers: 3,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['MR.L1I2U3', 'TLXX', 'GUOBANXIAN1'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '13',
  },
  {
    name: 'InvasionAU1',
    ipAddress: '103.42.224.189',
    port: 1234,
    mapId: 'media/packages/vanilla/maps/map1_2',
    mapName: '',
    bots: 183,
    country: 'Australia',
    currentPlayers: 3,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['MR. GREENJUJU', 'MILESGUO', 'SCROTUM BONGO'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '14',
  },
  {
    name: 'InvasionJP2',
    ipAddress: '45.32.63.85',
    port: 1235,
    mapId: 'media/packages/vanilla/maps/map5',
    mapName: '',
    bots: 111,
    country: 'Japan',
    currentPlayers: 3,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['ARKCEL', 'ALCHO', 'STORE'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '15',
  },
  {
    name: 'MARUISA',
    ipAddress: '111.30.122.128',
    port: 1490,
    mapId: 'media/packages/GFL_Castling/maps/map21',
    mapName: '',
    bots: 228,
    country: 'Not set',
    currentPlayers: 3,
    version: '1.98.1',
    dedicated: false,
    mod: 1,
    playerList: ['MARUISA', 'LAVAD', 'PHTILOPSIS'],
    comment: '',
    url: '',
    maxPlayers: 4,
    mode: '',
    realm: '',
    id: '16',
  },
  {
    name: 'ST',
    ipAddress: '45.195.22.113',
    port: 48188,
    mapId: 'media/packages/GFL_Castling/maps/map17',
    mapName: '',
    bots: 142,
    country: 'Not set',
    currentPlayers: 3,
    version: '1.98.1',
    dedicated: false,
    mod: 1,
    playerList: ['ST', 'KUROMITSUD', 'CARLISLE'],
    comment: '',
    url: '',
    maxPlayers: 3,
    mode: '',
    realm: '',
    id: '17',
  },
  {
    name: '915-DAGU',
    ipAddress: '128.1.156.90',
    port: 64767,
    mapId: 'media/packages/vanilla.desert/maps/map6',
    mapName: '',
    bots: 149,
    country: 'Not set',
    currentPlayers: 2,
    version: '1.98.1',
    dedicated: false,
    mod: 0,
    playerList: ['DAGU511', 'T-F'],
    comment: '',
    url: '',
    maxPlayers: 64,
    mode: '',
    realm: '',
    id: '18',
  },
  {
    name: 'COLONEL PIG',
    ipAddress: '94.143.240.220',
    port: 2324,
    mapId: 'media/packages/vanilla/maps/map5',
    mapName: '',
    bots: 117,
    country: 'Not set',
    currentPlayers: 2,
    version: '1.98.1',
    dedicated: false,
    mod: 0,
    playerList: ['TBP', 'MR. GREEN'],
    comment: '',
    url: '',
    maxPlayers: 2,
    mode: '',
    realm: '',
    id: '19',
  },
  {
    name: 'HAHA',
    ipAddress: '120.85.107.135',
    port: 18151,
    mapId: 'media/packages/vanilla/maps/map7',
    mapName: '',
    bots: 71,
    country: 'Not set',
    currentPlayers: 2,
    version: '1.98.1',
    dedicated: false,
    mod: 0,
    playerList: ['HAHA', 'MR. GREEN'],
    comment: '',
    url: '',
    maxPlayers: 2,
    mode: '',
    realm: '',
    id: '20',
  },
  {
    name: 'InvasionUS2',
    ipAddress: '162.248.88.126',
    port: 1234,
    mapId: 'media/packages/vanilla/maps/map13',
    mapName: '',
    bots: 171,
    country: 'USA, Chicago',
    currentPlayers: 2,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['KBAI', 'KONGBAI'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '21',
  },
  {
    name: 'WW2InvasionEU2',
    ipAddress: '185.107.96.42',
    port: 1290,
    mapId: 'media/packages/pacific/maps/island3',
    mapName: '',
    bots: 113,
    country: 'Germany',
    currentPlayers: 2,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['MR. GREENDSCDFCF', 'ASDAASDASDASDQAW'],
    comment: 'WW2 Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_pacific',
    id: '22',
  },
  {
    name: '[Castling][Normal LV3]',
    ipAddress: '49.235.149.243',
    port: 1236,
    mapId: 'media/packages/GFL_Castling/maps/map2_c',
    mapName: '',
    bots: 195,
    country: 'China',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: ['YS323'],
    comment:
      'Read server rules in our discord: discord.gg/wwUM3kYmRC, QQ Group: 706234535',
    url: 'https://castling.fandom.com/wiki/Castling_Wiki',
    maxPlayers: 15,
    mode: 'Castling',
    realm: '',
    id: '23',
  },
  {
    name: 'GFLNP[CN04][Extreme][Loot]',
    ipAddress: '117.21.200.85',
    port: 60004,
    mapId: 'media/packages/vanilla/maps/map3',
    mapName: '',
    bots: 126,
    country: 'China',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: ['YOU123'],
    comment: 'GFL mod QQ qun:  586155883',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2513537759',
    maxPlayers: 24,
    mode: 'GFL [INF]',
    realm: '',
    id: '24',
  },
  {
    name: 'InvasionEU1',
    ipAddress: '185.107.96.42',
    port: 1234,
    mapId: 'media/packages/vanilla.desert/maps/map6',
    mapName: '',
    bots: 138,
    country: 'Germany',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['SPIRIGGAN'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '25',
  },
  {
    name: 'InvasionUS1',
    ipAddress: '162.248.88.126',
    port: 1236,
    mapId: 'media/packages/vanilla/maps/map21',
    mapName: '',
    bots: 261,
    country: 'USA, Chicago',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['A-GEN'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '26',
  },
  {
    name: 'InvasionUSWest1',
    ipAddress: '162.248.93.251',
    port: 1234,
    mapId: 'media/packages/vanilla.desert/maps/map6',
    mapName: '',
    bots: 138,
    country: 'USA, LA',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['NIU'],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: 'official_invasion',
    id: '27',
  },
  {
    name: 'LILIYA',
    ipAddress: '112.224.195.102',
    port: 34446,
    mapId: 'media/packages/vanilla/maps/map2',
    mapName: '',
    bots: 99,
    country: 'Not set',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: false,
    mod: 1,
    playerList: ['LILIYA'],
    comment: '',
    url: '',
    maxPlayers: 6,
    mode: '',
    realm: '',
    id: '28',
  },
  {
    name: 'MUSUSU',
    ipAddress: '14.19.28.219',
    port: 32536,
    mapId: 'media/packages/GFL_Castling/maps/map21',
    mapName: '',
    bots: 332,
    country: 'Not set',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: false,
    mod: 1,
    playerList: ['MUSUSU'],
    comment: '',
    url: '',
    maxPlayers: 9,
    mode: '',
    realm: '',
    id: '29',
  },
  {
    name: 'RST',
    ipAddress: '125.40.105.15',
    port: 33959,
    mapId: 'media/packages/GFL_Castling/maps/map2_c',
    mapName: '',
    bots: 163,
    country: 'Not set',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: false,
    mod: 1,
    playerList: ['RST'],
    comment: '',
    url: '',
    maxPlayers: 2,
    mode: '',
    realm: '',
    id: '30',
  },
  {
    name: 'WW2InvasionUS2',
    ipAddress: '162.248.88.126',
    port: 1290,
    mapId: 'media/packages/pacific/maps/island8',
    mapName: '',
    bots: 209,
    country: 'USA, Chicago',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: ['MR.DDDAVID'],
    comment: 'WW2 Coop campaign',
    url: '',
    maxPlayers: 24,
    mode: 'COOP',
    realm: 'official_pacific',
    id: '31',
  },
  {
    name: '[Castling][Global][Russia LV1]',
    ipAddress: '46.174.52.235',
    port: 1234,
    mapId: 'media/packages/GFL_Castling/maps/map10',
    mapName: '',
    bots: 156,
    country: 'Russia',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment:
      '(1.0:1.5)Read server rules in our discord: discord.gg/wwUM3kYmRC, QQ Group: 706234535',
    url: 'https://castling.fandom.com/wiki/Castling_Wiki',
    maxPlayers: 30,
    mode: 'Castling',
    realm: '',
    id: '32',
  },
  {
    name: '[Castling][TEST-1 LV4]',
    ipAddress: '39.89.216.234',
    port: 1235,
    mapId: 'media/packages/GFL_Castling/maps/map2_c',
    mapName: '',
    bots: 152,
    country: 'China,Qingdao',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: 'This server is currently testing and may closed anytime',
    url: 'https://castling.fandom.com/wiki/Castling_Wiki',
    maxPlayers: 10,
    mode: 'Castling',
    realm: '',
    id: '33',
  },
  {
    name: '[地狱潜兵] 挂机/抽卡/赛车服',
    ipAddress: '110.42.109.166',
    port: 1244,
    mapId: 'media/packages/hell_diver/maps/race1',
    mapName: '',
    bots: 0,
    country: 'Not set',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: '地狱潜兵模组  QQ：498520233 1倍xp',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2910392031',
    maxPlayers: 32,
    mode: 'HD Race',
    realm: '',
    id: '34',
  },
  {
    name: '[地狱潜兵] 难度 12-困难',
    ipAddress: '110.42.109.166',
    port: 2334,
    mapId: 'media/packages/hell_diver/maps/map7',
    mapName: '',
    bots: 360,
    country: 'Not set',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: '地狱潜兵模组  QQ：498520233 1.2倍xp',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2910392031',
    maxPlayers: 16,
    mode: 'HD L12',
    realm: '',
    id: '35',
  },
  {
    name: '[地狱潜兵]僵尸服-5/俯视角',
    ipAddress: '110.42.109.166',
    port: 1247,
    mapId: 'media/packages/hell_diver/maps/map8_2',
    mapName: '',
    bots: 0,
    country: 'Not set',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: '僵尸模式，同步存档。 地狱潜兵模组  QQ：498520233',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2910392031',
    maxPlayers: 8,
    mode: 'HD Zombie',
    realm: '',
    id: '36',
  },
  {
    name: 'CT少前',
    ipAddress: '39.78.113.75',
    port: 1234,
    mapId: 'media/packages/GFL_Castling/maps/map12',
    mapName: '',
    bots: 190,
    country: '中华人民共和国',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: '公益服',
    url: 'https://castling.fandom.com/wiki/Castling_Wiki',
    maxPlayers: 24,
    mode: 'GFL_Castling',
    realm: '',
    id: '37',
  },
  {
    name: 'DominanceASIA2',
    ipAddress: '47.107.163.15',
    port: 1290,
    mapId: 'media/packages/vanilla/maps/map18',
    mapName: '',
    bots: 66,
    country: 'China',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [''],
    comment: 'Dominance PvP',
    url: '',
    maxPlayers: 32,
    mode: 'DOM',
    realm: 'official_dominance',
    id: '38',
  },
  {
    name: 'DominanceEU1',
    ipAddress: '185.107.96.42',
    port: 1260,
    mapId: 'media/packages/vanilla/maps/map7',
    mapName: '',
    bots: 67,
    country: 'Germany',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [''],
    comment: 'Dominance PvP',
    url: '',
    maxPlayers: 64,
    mode: 'DOM',
    realm: 'official_dominance',
    id: '39',
  },
  {
    name: 'DominanceUS1',
    ipAddress: '162.248.88.126',
    port: 1238,
    mapId: 'media/packages/vanilla/maps/map11',
    mapName: '',
    bots: 52,
    country: 'USA, Chicago',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [''],
    comment: 'Dominance PvP',
    url: '',
    maxPlayers: 64,
    mode: 'DOM',
    realm: 'official_dominance',
    id: '40',
  },
  {
    name: 'GFL:Verses of Iron[CN1]',
    ipAddress: '150.158.20.54',
    port: 1234,
    mapId: 'media/packages/GFL1_inf_i/maps/map6_2',
    mapName: '',
    bots: 135,
    country: 'China',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment:
      '[新人首选]闪退+QQ群: 588522175少女还是机甲？嗯！都不错！ 100%XP 300%RP',
    url: '',
    maxPlayers: 20,
    mode: 'GFL [INF]',
    realm: '',
    id: '41',
  },
  {
    name: 'GFLNP[FOB]',
    ipAddress: '117.21.200.85',
    port: 60000,
    mapId: 'media/packages/GFLNP_INF/maps/fob',
    mapName: '',
    bots: 0,
    country: 'China',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: 'GFL mod QQ qun: 748950999 / 1072742936（满）',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2513537759',
    maxPlayers: 32,
    mode: 'GFL [FOB]',
    realm: '',
    id: '42',
  },
  {
    name: 'Imba > Azur Lane #1',
    ipAddress: '124.223.113.204',
    port: 50170,
    mapId: 'media/packages/vanilla.desert/maps/map6',
    mapName: '',
    bots: 135,
    country: 'China, Shanghai',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: 'QQ群:837341470,1倍AI量,90精准度',
    url: 'https://rwr-imba-server-doc.kreedzt.com/azur_lane/user_manual/',
    maxPlayers: 18,
    mode: 'Azur Lane',
    realm: '',
    id: '43',
  },
  {
    name: 'Imba > GFLNP #12',
    ipAddress: '124.223.113.204',
    port: 50168,
    mapId: 'media/packages/vanilla.desert/maps/map9',
    mapName: '',
    bots: 442,
    country: 'China, Shanghai',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: 'QQ群:837341470,入群有奖励,2倍XP与AI,测试难度,+20%掉落,每周发放cb',
    url: 'https://rwr-imba-server-doc.kreedzt.com/gflnp/user_manual/',
    maxPlayers: 18,
    mode: 'Extra',
    realm: '',
    id: '44',
  },
  {
    name: 'Imba > GFLNP #3',
    ipAddress: '124.222.46.179',
    port: 50167,
    mapId: 'media/packages/vanilla/maps/map3',
    mapName: '',
    bots: 224,
    country: 'China, Shanghai',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: 'QQ群:837341470,入群有奖励,2倍XP与AI,1级难度,每周发放cb',
    url: 'https://rwr-imba-server-doc.kreedzt.com/gflnp/user_manual/',
    maxPlayers: 18,
    mode: 'Normal',
    realm: '',
    id: '45',
  },
  {
    name: 'Imba > GFLNP #5',
    ipAddress: '124.223.113.204',
    port: 50167,
    mapId: 'media/packages/vanilla.desert/maps/map9',
    mapName: '',
    bots: 442,
    country: 'China, Shanghai',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: 'QQ群:837341470,入群有奖励,2倍XP与AI,2级难度,+5%掉落,每周发放cb',
    url: 'https://rwr-imba-server-doc.kreedzt.com/gflnp/user_manual/',
    maxPlayers: 18,
    mode: 'Hard',
    realm: '',
    id: '46',
  },
  {
    name: 'Imba > GFLNP #7',
    ipAddress: '124.223.71.223',
    port: 50167,
    mapId: 'media/packages/vanilla.desert/maps/map9',
    mapName: '',
    bots: 442,
    country: 'China, Shanghai',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment: 'QQ群:837341470,入群有奖励,2倍XP与AI,3级难度,+10%掉落,每周发放cb',
    url: 'https://rwr-imba-server-doc.kreedzt.com/gflnp/user_manual/',
    maxPlayers: 18,
    mode: 'Insane',
    realm: '',
    id: '47',
  },
  {
    name: 'MyInvasion',
    ipAddress: '120.229.54.224',
    port: 40256,
    mapId: 'media/packages/vanilla/maps/map2',
    mapName: '',
    bots: 98,
    country: 'Not set',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [''],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: '',
    id: '48',
  },
  {
    name: 'MyInvasion',
    ipAddress: '113.4.243.14',
    port: 1240,
    mapId: 'media/packages/vanilla/maps/map13_2',
    mapName: '',
    bots: 152,
    country: 'Not set',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [''],
    comment: 'Coop campaign',
    url: '',
    maxPlayers: 32,
    mode: 'COOP',
    realm: '',
    id: '49',
  },
  {
    name: 'WW2InvasionEU1',
    ipAddress: '185.107.96.42',
    port: 1280,
    mapId: 'media/packages/edelweiss/maps/edelweiss2',
    mapName: '',
    bots: 202,
    country: 'Germany',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [''],
    comment: 'WW2 Coop campaign',
    url: '',
    maxPlayers: 24,
    mode: 'COOP',
    realm: 'official_pacific',
    id: '50',
  },
  {
    name: 'GFLNP[CN03][Hard][Loot]',
    ipAddress: '117.21.200.85',
    port: 60003,
    mapId: 'media/packages/vanilla/maps/map2',
    mapName: '',
    bots: 108,
    country: 'China',
    currentPlayers: 1,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: ['MR. MICHAEL-1000'],
    comment: 'GFL mod QQ qun: 586155883（满）',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2513537759',
    maxPlayers: 24,
    mode: 'GFL [INF]',
    realm: '',
    id: '51',
  },
  {
    name: 'GFLNP[CN02][Easy][LT]',
    ipAddress: '117.21.200.85',
    port: 60002,
    mapId: 'media/packages/vanilla/maps/map1_2',
    mapName: '',
    bots: 147,
    country: 'China',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 1,
    playerList: [''],
    comment:
      '新手服 Servers for starters. 75% enemies, 80% XP.  GFL mod QQ qun: 748950999 / 1072742936（满）',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2513537759',
    maxPlayers: 24,
    mode: 'GFL [INF]',
    realm: '',
    id: '52',
  },
  {
    name: 'WW2InvasionUS1',
    ipAddress: '162.248.88.126',
    port: 1280,
    mapId: 'media/packages/pacific/maps/island4',
    mapName: '',
    bots: 127,
    country: 'USA, Chicago',
    currentPlayers: 0,
    version: '1.98.1',
    dedicated: true,
    mod: 0,
    playerList: [''],
    comment: 'WW2 Coop campaign',
    url: '',
    maxPlayers: 24,
    mode: 'COOP',
    realm: 'official_pacific',
    id: '53',
  },
];
